version: '2'

services:
  peer-base:
    image: connectathon/fabric-peer
    restart: unless-stopped
    environment: 
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=marbles_net
      - CORE_LOGGING_LEVEL=DEBUG
    volumes: 
    - /var/run:/host/var/run/
    command: peer node start
